source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MDComponents_Example', :exclusive => true do
  pod "MDComponents", :path => "../"
end

target 'MDComponents_Tests', :exclusive => true do
  pod "MDComponents", :path => "../"

  
end
